[colors.primary]
foreground = "#4c4f69"
background = "#eff1f5"

[colors.cursor]
text = "#eff1f5"
cursor = "#dc8a78"

[colors.selection]
text = "#4c4f69"
background = "#d8dae1"

[colors.normal]
black = "#5c5f77"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#acb0be"

[colors.bright]
black = "#6c6f85"
red = "#de293e"
green = "#49af3d"
yellow = "#eea02d"
blue = "#456eff"
magenta = "#fe85d8"
cyan = "#2d9fa8"
white = "#bcc0cc"
