[colors.primary]
foreground = "#cdd6f4"
background = "#1e1e2e"

[colors.cursor]
text = "#11111b"
cursor = "#f5e0dc"

[colors.selection]
text = "#cdd6f4"
background = "#353748"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.bright]
black = "#585b70"
red = "#f37799"
green = "#89d88b"
yellow = "#ebd391"
blue = "#74a8fc"
magenta = "#f2aede"
cyan = "#6bd7ca"
white = "#bac2de"
